global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

scrape_configs:
  - job_name: 'ai-music-mastering-api'
    static_configs:
      - targets: ['api:8000']
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: 'model-services'
    static_configs:
      - targets: 
        - 'music-gen-service:8000'
        - 'stable-audio-service:8000'
        - 'music-lm-service:8000'
        - 'audiocraft-service:8000'
        - 'jukebox-service:8000'
        - 'melody-rnn-service:8000'
        - 'music-vae-service:8000'
        - 'aces-service:8000'
        - 'rhythm-service:8000'
        - 'suni-service:8000'
        - 'beethoven-service:8000'
        - 'mureka-service:8000'
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: 'postgres'
    static_configs:
      - targets: ['db:5432']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093